### ISSUE TITLE
Gemfile.lock issue

### ISSUE THREAD

**Issue by geoffmcl** [htacg/html-tidy.org#12]
Get this report...

```
We found potential security vulnerabilities in your dependencies.
Some of the dependencies defined in these manifest files have known security vulnerabilities and should be updated:

Gemfile.lock 4 vulnerabilities found
Only users who have been granted access to vulnerability alerts for this repository can see this message.
Learn more about vulnerability alerts
```

How to fix? feedback welcomed... thanks...

**Comment by geoffmcl** [comment]
Hmmm, got some more of these notices, but also includes auto PR's #15 nd #16, via `dependabot`, so will shortly merge these... hopefully fixes the problem...

**Comment by geoffmcl** [comment]
The 3 new email notices I received are `vulnerability` in -

  - redcloth < 4.3.0 defined in Gemfile.lock. 
  - jekyll < 3.6.3 defined in Gemfile.lock. 
  - nokogiri >= 1.6.0, < 1.6.8 defined in Gemfile.lock. 
  
But the PR's seem to address only one -

   - #15 Bump nokogiri from 1.6.7.2 to 1.10.4 
   - #16 Bump ffi from 1.9.10 to 1.11.1

and even that is different versions for `nokogiri`...

Wow, how to understand, and update to the best latest versions...

Will try the PR's and attempt to understand this... but any help welcome... thanks...

**Comment by geoffmcl** [comment]
That worked, and addresses some... What more?

How to test the Gemfile.lock for others, and choose the correct version for each...

Any help, ideas, etc... very welcome... thanks...

**Comment by balthisar** [comment]
@geoffmcl, I took care of it. The Gemfile.lock shouldn't be edited directly; it represents the "frozen" version of the gems (dependencies) used to run the website. A quick 'bundle update' from zsh updated all of them to the latest, and I pushed this.

**Comment by geoffmcl** [comment]
@balthisar thanks...
