### ISSUE TITLE
html-tidy site does not work with https

### ISSUE THREAD

**Issue by sgbeal** [htacg/html-tidy.org#18]
The site:

http://www.html-tidy.org/

does not work when loaded with an HTTPS scheme because it loads it resources explicitly over HTTP, and some browsers do not like switching from secure to insecure connections when loading resources.

The fix is to change all  of the explicit "http://" resource-loading URLs to "//" (removing the http: prefix), which will allow it to work with both http and https.

**Comment by balthisar** [comment]
Fixed. Thanks.
